"""initial schema

Revision ID: 4de5f6f25974
Revises: 
Create Date: 2026-05-25 18:24:42.284920
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op



revision: str = '4de5f6f25974'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_tickets',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('state_fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('followup_written', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('runtime_config',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runtime_config')
    op.drop_table('processed_tickets')
    # ### end Alembic commands ###
