"""referential cache + group routing

Revision ID: 9c98056f21af
Revises: 10d94fc32654
Create Date: 2026-05-25 19:29:54.343074
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op



revision: str = '9c98056f21af'
down_revision: str | None = '10d94fc32654'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referential_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ext_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('skills', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'ext_id', name='uq_referential_kind_ext')
    )
    with op.batch_alter_table('referential_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referential_cache_kind'), ['kind'], unique=False)

    op.drop_table('tech_profiles')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_column('group_id')

    op.create_table('tech_profiles',
    sa.Column('technician_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('profile', sa.VARCHAR(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('technician_id')
    )
    with op.batch_alter_table('referential_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referential_cache_kind'))

    op.drop_table('referential_cache')
    # ### end Alembic commands ###
