"""referential_cache profile column

Revision ID: cb8ffef4f8f3
Revises: 9c98056f21af
Create Date: 2026-05-25 21:16:21.718277
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op



revision: str = 'cb8ffef4f8f3'
down_revision: str | None = '9c98056f21af'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referential_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referential_cache', schema=None) as batch_op:
        batch_op.drop_column('profile')

    # ### end Alembic commands ###
